pipeline:
  build:
    image: debian:buster-slim
    pull: true
    commands:
      - apt-get update
      - apt-get install -y build-essential cmake pkg-config
      - apt-get install -y libcurl4-openssl-dev libcurlpp-dev libjsoncpp-dev libxdg-basedir-dev
      - apt-get install -y curl
      - curl -so mastodon-cpp.deb https://schlomp.space/attachments/b3119713-4c05-4acc-9cb4-460b15e19279
      - dpkg -i mastodon-cpp.deb
      - mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install
