pipeline:
  download:
    image: plugins/download
    pull: true
    source: https://schlomp.space/attachments/5ab8f994-669a-47f8-8ac7-ed5902ad0339
    destination: mastodon-cpp.deb

  gcc6:
    image: debian:stretch-slim
    pull: true
    environment:
      - LANG=C.utf8
      - CXX=g++-6
      - CXXFLAGS=-pipe -O2
    commands:
      - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
      - echo "deb http://deb.debian.org/debian sid main" >> /etc/apt/sources.list.d/sid.list
      - apt-get update -q
      - apt-get install -qy build-essential cmake pkg-config
      - apt-get install -qy libjsoncpp-dev libcurl4-openssl-dev libxdg-basedir-dev
      - apt-get install -qy -t sid libcurlpp-dev
      - dpkg -i mastodon-cpp.deb
      - rm -rf build && mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install

  gcc7:
    image: debian:stretch-slim
    pull: true
    environment:
      - LANG=C.utf8
      - CXX=g++-7
      - CXXFLAGS=-pipe -O2
    commands:
      - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
      - echo "deb http://deb.debian.org/debian sid main" >> /etc/apt/sources.list.d/sid.list
      - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" >> /etc/apt/sources.list.d/ubuntu-toolchain-r.list
      - apt-get update -q
      - apt-get install -qy gnupg
      - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 0x60c317803a41ba51845e371a1e9377a2ba9ef27f
      - gpg --armor --export 0x60c317803a41ba51845e371a1e9377a2ba9ef27f | apt-key add -
      - apt-get update -q
      - apt-get install -qy build-essential cmake pkg-config
      - apt-get install -qy -t xenial g++-7
      - apt-get install -qy libjsoncpp-dev libcurl4-openssl-dev libxdg-basedir-dev
      - apt-get install -qy -t sid libcurlpp-dev
      - dpkg -i mastodon-cpp.deb
      - rm -rf build && mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install

  gcc8:
    image: debian:stretch-slim
    pull: true
    environment:
      - LANG=C.utf8
      - CXX=g++-8
      - CXXFLAGS=-pipe -O2
    commands:
      - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
      - echo "deb http://deb.debian.org/debian sid main" >> /etc/apt/sources.list.d/sid.list
      - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" >> /etc/apt/sources.list.d/ubuntu-toolchain-r.list
      - apt-get update -q
      - apt-get install -qy gnupg
      - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 0x60c317803a41ba51845e371a1e9377a2ba9ef27f
      - gpg --armor --export 0x60c317803a41ba51845e371a1e9377a2ba9ef27f | apt-key add -
      - apt-get update -q
      - apt-get install -qy build-essential cmake pkg-config
      - apt-get install -qy -t xenial g++-8
      - apt-get install -qy libjsoncpp-dev libcurl4-openssl-dev libxdg-basedir-dev
      - apt-get install -qy -t sid libcurlpp-dev
      - dpkg -i mastodon-cpp.deb
      - rm -rf build && mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install

  notify:
    image: drillster/drone-email
    pull: true
    host: cryptoparty-celle.de
    secrets: [ email_username, email_password ]
    from: drone@tzend.de
    when:
      status: [ changed, failure ]
