pipeline:
  download:
    image: plugins/download
    source: https://schlomp.space/attachments/dbc2b2b0-86c9-4aee-ac99-9cb9e91a82ed
    destination: mastodon-cpp.deb
  build:
    image: debian:buster-slim
    pull: true
    commands:
      - apt-get update -q
      - apt-get install -qy build-essential cmake pkg-config
      - apt-get install -qy libcurl4-openssl-dev libcurlpp-dev libjsoncpp-dev libxdg-basedir-dev
      - dpkg -i mastodon-cpp.deb
      - mkdir -p build && cd build
      - cmake ..
      - make VERBOSE=1
      - make install DESTDIR=install
  notify:
    image: drillster/drone-email
    host: cryptoparty-celle.de
    secrets: [ email_username, email_password ]
    from: drone@tzend.de
    when:
      status: [ changed, failure ]
